### ISSUE TITLE
MCP: Exception("MCPLockError('MCPQueue.queue: Cannot lock MCP.') 

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2919]
I see this too often and in one instance it lead to #2918 

All benign but to me it feels like the system architecture comes crumbling down on us. Kiosk is not designed to be a multi-project online system.

**Comment by urapadmin** [comment]
this has not come up at all lately. I cannot find a single instance in either PVD or ANC. The only ones I can find are in BUAP with the latest one in November 2024: 

```
[9988/11692: app.ERROR at 2024-11-01 15:21:38,716]: Exception on /api/syncmanager/v1/workstations [GET]
Traceback (most recent call last):
  File "E:\buap\kiosk\plugins\syncmanagerplugin\syncmanagerapi.py", line 193, in get
    if self.gather_job_information(result, sync_manager):
  File "E:\buap\kiosk\plugins\syncmanagerplugin\syncmanagerapi.py", line 234, in gather_job_information
    for ws_job in sync_manager.list_latest_workstation_jobs():
  File "E:\buap\kiosk\plugins\syncmanagerplugin\kiosksyncmanager.py", line 151, in list_latest_workstation_jobs
    jobs = self.workstation_jobs.fetch_workstation_jobs()
  File "e:\buap\kiosk\plugins\syncmanagerplugin\kioskworkstationjobs.py", line 62, in fetch_workstation_jobs
    job = KioskWorkstationJob(MCPJob(self._general_store, job_id))
  File "e:\buap\kiosk\sync\sync\core\mcpinterface\mcpjob.py", line 126, in __init__
    self._fetch(lock_queue=lock_queue)
  File "e:\buap\kiosk\sync\sync\core\mcpinterface\mcpjob.py", line 404, in _fetch
    data = self._queue.read(self.job_id, lock_queue=lock_queue)
  File "e:\buap\kiosk\sync\sync\core\mcpinterface\mcpqueue.py", line 89, in read
    lock = self.lock()
  File "e:\buap\kiosk\sync\sync\core\mcpinterface\mcpqueue.py", line 37, in lock
    raise MCPLockError(f"{self.__class__.__name__}.queue: Cannot lock MCP.")
mcpinterface.mcpconstants.MCPLockError: MCPQueue.queue: Cannot lock MCP.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python310\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\python310\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\python310\lib\site-packages\flask_restful\__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "E:\python310\lib\site-packages\flask\views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "E:\python310\lib\site-packages\flask_restful\__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "E:\python310\lib\site-packages\flask_httpauth.py", line 174, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "E:\buap\kiosk\plugins\syncmanagerplugin\syncmanagerapi.py", line 213, in get
    flask.abort(500, description=repr(e))
  File "E:\python310\lib\site-packages\flask\helpers.py", line 277, in abort
    current_app.aborter(code, *args, **kwargs)
  File "E:\python310\lib\site-packages\werkzeug\exceptions.py", line 861, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: MCPLockError('MCPQueue.queue: Cannot lock MCP.')

```

**Comment by urapadmin** [comment]
not a recent issue and I don't really see a pattern. It happened in all kinds of places and I don't think it is worth my time to hunt it down until we see it more often again and connected to real issues.

**Comment by urapadmin** [comment]
I have saved the all the BUAP logs from when  it happened in the test cases folder.

**Comment by luizaogs** [comment]
Close this? Seems like the latest instance was almost a year ago.

**Comment by urapadmin** [comment]
- no, I am still on #3248 which might be related.

**Comment by luizaogs** [comment]
Close?

**Comment by urapadmin** [comment]
let's
